# Nome da aplicação

spring.application.name=sistema-gestao-consultas



# 1. Conexão com o banco de dados PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_gestao_consultas

spring.datasource.username=postgres

spring.datasource.password=080519

spring.datasource.driver-class-name=org.postgresql.Driver



# 2. Configurações do Hibernate (JPA)



spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# 3. --- AJUSTE PARA O DATAINITIALIZER ---

# Desativado o modo de inicialização por SQL (import.sql) para não dar erro de duplicidade

spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=false



# 4. Configurações de Segurança (JWT)

# Esta chave deve ser a mesma no seu TokenService

api.security.token.secret=1234567890abcdef1234567890abcdef



# 5. Logs de Segurança para Debug

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG



# 6. Porta do Servidor

server.port=8082

